version: '3.3'
  
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql_api_person
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks: 
      - api-person-network

  back:
    image: samuelgenio28/back-api-person
    restart: always
    container_name: back
    build: ./back
    working_dir: /back
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/backapiperson
    volumes:
      - ./back:/back
      - ~/.m2:/root/.m2
    ports:
      - '8080:8080'
    command: mvn clean spring-boot:run
    links: 
      - db
    depends_on: 
      - db
    networks: 
      - api-person-network
  front:
    container_name: front
    build: ./front
    working_dir: /front
    ports:
      - '1337:80'
    networks: 
      - api-person-network

networks: 
  api-person-network:
    driver: bridge
